#pragma once

#define GPIO_LED_GREEN GPIO_NUM_33
#define GPIO_LED_ORANGE GPIO_NUM_32
#define GPIO_LED_RED GPIO_NUM_21

#define GPIO_BUZZER GPIO_NUM_4

#define GPIO_BTN_POWER GPIO_NUM_19
#define GPIO_BTN_BRIGHTNESS GPIO_NUM_18
#define GPIO_BTN_MODE GPIO_NUM_5

#define GPIO_LED_SDA GPIO_NUM_14
#define GPIO_LED_SCL GPIO_NUM_27

#define GPIO_EEPROM_SDA GPIO_NUM_36
#define GPIO_EEPROM_SCL GPIO_NUM_37

#define GPIO_MOTOR_PWM GPIO_NUM_26 // OUT
#define GPIO_MOTOR_BRK GPIO_NUM_2  // OUT
#define GPIO_MOTOR_FG GPIO_NUM_34  // IN
#define GPIO_MOTOR_5V GPIO_NUM_15  // OUT

// PS for particle sensor
#define GPIO_PMS_RX GPIO_NUM_16
#define GPIO_PMS_TX GPIO_NUM_17
#define GPIO_PMS_5V GPIO_NUM_13


// ESP32 peripherals

#define LEDC_TIMER_MOTOR_PWM LEDC_TIMER_0
#define LEDC_TIMER_RGB LEDC_TIMER_1
#define LEDC_TIMER_BUZZER LEDC_TIMER_2

#define LEDC_CHANNEL_MOTOR_PWM LEDC_CHANNEL_0
#define LEDC_CHANNEL_RGB_R LEDC_CHANNEL_1
#define LEDC_CHANNEL_RGB_G LEDC_CHANNEL_2
#define LEDC_CHANNEL_RGB_B LEDC_CHANNEL_3
#define LEDC_CHANNEL_BUZZER LEDC_CHANNEL_4

#define UART_PMS UART_NUM_1

#define BUZZER_FREQUENCY 2000
#define BUZZER_BEEP_TIME_MS 60

#define AUTO_GOOD_PERCENT 30
#define AUTO_FAIR_PERCENT 45
#define AUTO_MODERATE_PERCENT 60
#define AUTO_POOR_PERCENT 75
#define AUTO_VPOOR_PERCENT 90
#define AUTO_XPOOR_PERCENT 100
#define AUTO_UNKNOWN_PERCENT AUTO_GOOD_PERCENT

